### ISSUE TITLE
How to deal with callback after successful login?

### ISSUE THREAD

**Issue by Peragorn** [fa-fifi/keycloak-wrapper#29]
I run the example code. However, this example does not specify how to deal with redirection in the correct way.
In my case, after logging in, the web view remains open. When I close it manually, I get an error in the application with the following `PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: null, description: User cancelled flow], null, null).`
Otherwise, when I have specified an address in the `redirectUrl` parameter that is a deeplink, the webview is closed and the control returns to the mobile app but I still get the error` PlatformException(null_intent, Failed to authorize: Null intent received, null, null).`
Could I ask for some guidance on how to use this library properly?

**Comment by fa-fifi** [comment]
You can read the guidance provided in [pub.dev](https://pub.dev/packages/keycloak_wrapper).

Inside the example code, it listens to the authentication stream. Once the user logged in, it will redirect the user to the home screen. Based on the error, you probably input the wrong username or password. Can you screen record your login process and show it to me? Maybe that will make it easier for me to understand your issue. There's might be something wrong somewhere inside your code too.

**Comment by Peragorn** [comment]
I have created a test application according to the tutorial.
As you can see in the video after entering the correct data the window does not close. On the application side, authenticationStream also does not return a status change as you can see in the logs. After closing the web view there is a Failed to authorize error as you can see in the recording and the `keycloakWrapper.login(config)` method returns false.

https://github.com/fa-fifi/keycloak-wrapper/assets/5932566/0283ac44-5df2-45d1-b9e3-10c9193ce8d3

**Comment by fa-fifi** [comment]
Instead of using `redirectUrl`, can you use `bundleIdentifier` instead? Remove your `redirectUrl` and enter your app package inside the `bundleIdentifier`. Let's see how it goes.

**Comment by fa-fifi** [comment]
Change your redirectUrl to `https://www.keycloak.org/app` and let see how it goes first.

**Comment by bishoyabdmariam** [comment]
I have the same issue and I working on it ,please notify me if there is a solution

**Comment by fa-fifi** [comment]
@bishoyabdmariam @Peragorn 

1. Insert your app package name inside `bundleIdentifier` and remove your `redirectUrl`.
2. If that doesn't work, re-check your `redirectUrl`, make sure it is a valid url.

Please try these steps and let me know.

**Comment by Peragorn** [comment]
1. You can't do that because the bundleIdentifier might look like com.example.test_app. The plugin creates a redirectUrl based on the bundleIdentifier, so the following URL will be created: com.example.test_app://login-callback, which is an invalid URL.
2. If I enter the correct URL it will redirect me to the page in web view. If I enter a URL that is a deep link to the mobile app, then it closes the web view and takes me back to the app but with a login error.
@bishoyabdmariam  I have found a solution, but it is not a fix for the bug we are discussing. I used a different library that allows me to log into Keyclock without having to open Webview.

**Comment by fa-fifi** [comment]
@Peragorn 

I know how bundleIdentifier looks like but have you ever try it and see if it succeed or not? That's what I want to know because I use this package that way. If you tried my first method and failed please let me know. Don't say it won't working without trying. Help me to help you.

**Comment by Peragorn** [comment]
Of course, I tried that is why I wrote that it is an invalid URL and keyclock will not register it in the Valid redirect URIs section.

**Comment by bishoyabdmariam** [comment]
> 1. You can't do that because the bundleIdentifier might look like com.example.test_app. The plugin creates a redirectUrl based on the bundleIdentifier, so the following URL will be created: com.example.test_app://login-callback, which is an invalid URL.
> 2. If I enter the correct URL it will redirect me to the page in web view. If I enter a URL that is a deep link to the mobile app, then it closes the web view and takes me back to the app but with a login error.
>    @bishoyabdmariam  I have found a solution, but it is not a fix for the bug we are discussing. I used a different library that allows me to log into Keyclock without having to open Webview.

what is this library ?

**Comment by Peragorn** [comment]
@bishoyabdmariam  [flutter_keycloak](https://pub.dev/packages/flutter_keycloak)

**Comment by bishoyabdmariam** [comment]
@Peragorn can you tell me what did you do in scopes ?

**Comment by Peragorn** [comment]
I use as scope "offline_access" but generally speaking it depends on the settings on the keyclock side.

**Comment by bishoyabdmariam** [comment]
E/flutter ( 1911): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'int' of 'index'

I have faced this error how you solved it  ?

**Comment by Peragorn** [comment]
No. Try log in on my way. One important note is(when keyclock is host by local env)  do not use localhost or 127.0.0.1 as authServerUrl, try something like that http://192.168.x.xxx:8080
`      Map conf = {
        'resource': KeyCloakConst.clientId,
        'realm': KeyCloakConst.realm,
        'auth-server-url': KeyCloakConst.authServerUrl,
      };
      await _flutterKeycloak.login(conf, username, password,
          scope: KeyCloakConst.scope);`

**Comment by bishoyabdmariam** [comment]
@Peragorn  it works thankyou but there is still an issue that there is no sign up how should I handle this ?

**Comment by bishoyabdmariam** [comment]
@fa-fifi have you reached the solution

**Comment by bishoyabdmariam** [comment]
@Peragorn please tell me how should I handle the sign up proccess ?

**Comment by fa-fifi** [comment]
> 1. You can't do that because the bundleIdentifier might look like com.example.test_app. The plugin creates a redirectUrl based on the bundleIdentifier, so the following URL will be created: com.example.test_app://login-callback, which is an invalid URL.

Hi @Peragorn 👋

You should insert `com.example:test_app:/*` instead of `com.example.test_app://login-callback` into the valid redirect URI and use my plugin as usual using `bundleIdentifier` instead of setting your own custom redirect URI. You should also set the same URI for valid post logout redirect URI.

@bishoyabdmariam Can u try my suggestion and see if it works?

**Comment by fa-fifi** [comment]
> 1. You can't do that because the bundleIdentifier might look like com.example.test_app. The plugin creates a redirectUrl based on the bundleIdentifier, so the following URL will be created: com.example.test_app://login-callback, which is an invalid URL.

Hi @Peragorn 👋
 
You shouldn't insert '_' (underscore) inside your app's `bundleIdentifier`. So, in this case, `com.example.test_app://login-callback` is considered invalid due to the underscore. Rename you app package name, then set your valid redirect URI inside your keycloak admin console as `<bundle_identifier>:/*` and retry using the `bundleIdentifier` parameter instead of setting your own custom `redirectUrl`.

Hope this helps. 🙏

**Comment by bishoyabdmariam** [comment]
I tried the changes that you made that it opens the webview and there is an error invalid parameter: redirect_uri

**Comment by fa-fifi** [comment]
@bishoyabdmariam go to your keycloak client's access settings and add `<bundle_identifier>:/*` into the valid redirect uri.

**Comment by bishoyabdmariam** [comment]
![image](https://github.com/fa-fifi/keycloak-wrapper/assets/75948543/caeb1b7a-d568-41d1-9dfb-2997d52397dc)
I have already done that

**Comment by kstan79** [comment]
i'm tested this package, run flutter in macosx. So far it can propup login page, can sign in, and pop up dialog close but application freeze and vscode focus here. 

<img width="1129" alt="image" src="https://github.com/fa-fifi/keycloak_wrapper/assets/1889979/07fb0da3-92ed-4e47-b01a-9adca6a604be">

i tried to implement try catch but i cant get any info

**Comment by fa-fifi** [comment]
@kstan79 Hi, there! 👋

Sorry for the late reply since I don't open my laptop on weekends.

Regarding your issue, I need more time to investigate it but would you mind to open a new issue? This issue that you commenting on is already closed and not related to your problem. Sorry for the inconvenience but i'll try my best to help you.
