### ISSUE TITLE
Platform Expection(Stale Token)

### ISSUE THREAD

**Issue by Tolutoon** [fa-fifi/keycloak-wrapper#31]
I keep getting this error on initializing my flutter application

[keycloak_wrapper] PlatformException 
(PlatformException(token_failed, Failed to get token: [error: invalid_grant, description: Stale token], null, null))

**Comment by fa-fifi** [comment]
Can you provide more context into this issue?

**Comment by Tolutoon** [comment]
I keep getting this error: 

AssertionError ('package:keycloak_wrapper/src/wrapper.dart': Failed assertion: 'isInitialized': Make sure the package has been initialized prior to calling this method.)

Below I have also attached a screenshot to it looks like.

<img width="1280" alt="Screen Shot 2024-03-05 at 11 34 29 AM" src="https://github.com/fa-fifi/keycloak-wrapper/assets/103889304/eedbd3a7-4183-4f6a-8737-7c629e5d41f8">

**Comment by fa-fifi** [comment]
It means you didn't initialized this package inside your `main` method but this error is different than the previous one. 🤔

**Comment by fa-fifi** [comment]
If you truly follow the example, then your Keycloak configuration is probably wrong. Double check your given values and also check your Keycloak Admin Console settings too.

**Comment by Tolutoon** [comment]
I tried the first option. Same thing.

For the example, I replaced the Configuration with my values (Bundle ID, Realm, Client ID...).
Same Error.

**Comment by fa-fifi** [comment]
Would u mind to give me your Keycloak configuration values so I can double check it?

**Comment by Tolutoon** [comment]
Here you go:
```
    bundleIdentifier: 'com.issl.test',
      clientId: 'flutter-cli',
      frontendUrl: 'https://keycloak.issl.ng',
      realm: 'Testing',
```

**Comment by Tolutoon** [comment]
It's a Token thing. I was able to clear the cache & restarted the App.

Thank you.
