### ISSUE TITLE
Update public api documentation

### ISSUE THREAD

**Issue by fa-fifi** [fa-fifi/keycloak-wrapper#5]
Refer to this [page](https://dart.dev/effective-dart/documentation) for effective dart documentation.

**Comment by DeleMike** [comment]
Hello @fa-fifi, 
I'm Michael and I would like to work on this issue. 
Can you clarify more about what you mean by updating the public API documentation?

**Comment by fa-fifi** [comment]
@DeleMike Just put comments for every publicly available methods explaining their purpose. No need to be too long. Just simple and concise, straight to the point. Make sure the grammar is correct and no typos. I already did some of them, and I don't expect you to do all of them. Just do what you can and I will double check them later. Please refer to this [link](https://dart.dev/effective-dart/documentation) on how to do documentation properly. Thanks btw. 😄

**Comment by DeleMike** [comment]
Hi @fa-fifi, 

Many thanks for your update. I discovered that most of the Public APIs are already documented. I just added docstring to where I believe there should be comments. What do you think? 

Also, I hope I am not missing anything, am I?
