### ISSUE TITLE
platform exception

### ISSUE THREAD

**Issue by bulletBane** [fa-fifi/keycloak-wrapper#8]
No refresh token found.
flutter: An error occured during logging user in.
flutter: PlatformException(authorize_and_exchange_code_failed, Failed to authorize: unauthorized_client: Invalid client or Invalid client credentials, null, null)

**Comment by fa-fifi** [comment]
That's not really an issue. The log just shows the error caught by the plugin when the user tried to login but failed, maybe due to a lost connection or invalid user credentials. Try to check with your backend regarding this issue, and feel free to reopen this issue if it persists.
